### ISSUE TITLE
SFML 2.4 and OpenTK 2.0

### ISSUE THREAD

**Issue by ghost** [graphnode/SFML.Net#2]
Hello

SFML.net  2.4 has been released, do you plan to update it? 

Same for opentk 2.0 :p

**Comment by graphnode** [comment]
I was waiting for the official CSFML 2.4 binary release but I will see what I can do.

**Comment by graphnode** [comment]
Done. Commit fbdc5dc5259b23a50240732d570613d3f6647bf5.
